In [ ]:
# Updating Keras
pip install -U keras

SyntaxError: ignored

In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import os
import cv2

base_dir = '/content/drive/My Drive/Colab Notebooks/Dataset GDPS'
os.mkdir(base_dir)


In [ ]:
# create a path to 'base_dir' to which we will join the names of the new folders
# train_dir
train_dir = os.path.join(base_dir, 'train_dir')
os.mkdir(train_dir)

# val_dir
val_dir = os.path.join(base_dir, 'val_dir')
os.mkdir(val_dir)



# [CREATE FOLDERS INSIDE THE TRAIN AND VALIDATION FOLDERS]
# Inside each folder we create seperate folders for each class

# create new folders inside train_dir
forged = os.path.join(train_dir, 'forged')
os.mkdir(forged)
genuine = os.path.join(train_dir, 'genuine')
os.mkdir(genuine)


# create new folders inside val_dir
forged = os.path.join(val_dir, 'forged')
os.mkdir(forged)
genuine = os.path.join(val_dir, 'genuine')
os.mkdir(genuine)

In [ ]:
# check that the folders have been created
import pandas as pd
import numpy as np
import os
import cv2
os.listdir(train_dir)

['forged', 'genuine']

In [ ]:
# check that the folders have been created
os.listdir(val_dir)

['forged', 'genuine']

In [ ]:
import os
from os import listdir
from numpy import asarray
from numpy import save
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
import shutil, os
folder = '/content/drive/My Drive/Dropbox/firmasSINTESISmanuscritas'

for r, d, f in os.walk(folder):
  for file in f:   
    if ".jpg" in file:
      if(file.startswith('c-', 0, 2)):
        shutil.copy(os.path.join(r, file), os.path.join( '/content/drive/My Drive/Colab Notebooks/Dataset GDPS/train_dir', 'genuine'))
      elif(file.startswith('cf', 0, 2)):
        shutil.copy(os.path.join(r, file), os.path.join('/content/drive/My Drive/Colab Notebooks/Dataset GDPS/train_dir', 'forged')) 
                 

In [ ]:
import shutil
import os
import numpy as np
import argparse
path='/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset'
path_to_data='/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train'
path_to_test_data='/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/Train'
def get_files_from_folder(path):
  files = os.listdir(path)
  return np.asarray(files)
# get dirs
for r, d, f in os.walk(path_to_data):
  for dirs in d:
    print(dirs) 
   
_, dirs, _ = next(os.walk(path_to_data))


# calculates how many train data per class
data_counter_per_class = np.zeros((len(dirs)))
print(len(dirs))
for i in range(len(dirs)):
  path = os.path.join(path_to_data, dirs[i])
  print(path)
  files = get_files_from_folder(path)
  print(len(files))
  data_counter_per_class[i] = len(files)
  print(data_counter_per_class[i])
  test_counter = np.round(data_counter_per_class * (1 - 0.8))
  print(test_counter)
# transfers files
for i in range(len(dirs)):
  path_to_original = os.path.join(path_to_data, dirs[i])
  path_to_save = os.path.join(path_to_test_data, dirs[i])
  print(path_to_original)
  print(path_to_save)
  if not os.path.exists(path_to_save):
    os.makedirs(path_to_save)
  files = get_files_from_folder(path_to_original)
  for j in range(int(test_counter[i])):
    dst = os.path.join(path_to_save, files[j])
    src = os.path.join(path_to_original, files[j])
    shutil.move(src, dst)

happy
fear
disgust
angry
surprise
neutral
sad
7
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/happy
2522
2522.0
[504.   0.   0.   0.   0.   0.   0.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/fear
2490
2490.0
[504. 498.   0.   0.   0.   0.   0.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/disgust
279
279.0
[504. 498.  56.   0.   0.   0.   0.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/angry
2375
2375.0
[504. 498.  56. 475.   0.   0.   0.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/surprise
2108
2108.0
[504. 498.  56. 475. 422.   0.   0.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/neutral
3738
3738.0
[504. 498.  56. 475. 422. 748.   0.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dataset/train/sad
4997
4997.0
[504. 498.  56. 475. 422. 748. 999.]
/content/drive/My Drive/Deep Learning FDP/Face Expression Dat

FileNotFoundError: ignored